version: 5.1.0
variant: default
logo:
  text: /dev/nvme0n1
head:
  favicon: /img/favicon.svg
  manifest:
    name: /dev/nvme0n1
    short_name:
    start_url:
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss:
navbar:
  menu:
    主页: /
    归档: archives
    分类: categories
    标签: tags
  links:
footer:
  links:
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: unfolded
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
sidebar:
  left:
    sticky: false
  right:
    sticky: true
widgets:
  - position: left
    type: profile
    author: 加大号的猫
    author_title: Midori Kochiya
    avatar: images/avatar.jpg
    avatar_rounded: true
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/kmod-midori
      Twitter:
        icon: fab fa-twitter
        url: https://twitter.com/enp39s0
      RSS:
        icon: fas fa-rss
        url: /
  - position: left
    type: links
    links:
      VtuberMusic: https://vtbmusic.com/
  - position: left
    type: categories
  - position: right
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: right
    type: recent_posts
  - position: right
    type: archives
  - position: right
    type: tags
plugins:
  animejs: true
  back_to_top: true
  gallery: true
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
